// eslint-disable-next-line no-shadow
export enum ProjectTechnology {
  React = 'React',
  TypeScript = 'TS',
  JavaScript = 'JS',
  HTML = 'Html',
  CSS = 'CSS',
  NextJS = 'NextJS',
  StyledComponents = 'Styled Components',
  NestJS = 'NestJS',
  NodeJS = 'NodeJs',
  Express = 'Express',
  Redux = 'Redux',
  ChakraUI = 'Chakra UI',
  TailwindCSS = 'TailwindCSS',
  'C++' = 'C++',
  OpenGl = 'OpenGL',
  Assimp = 'Assimp',
  GLFW = 'GLFW',
  ImGui = 'ImGui',
  GLSL = 'GLSL',
  GLM = 'GLM',
  Premake5 = 'Premake5',
}
